# Generated by Django 5.2.1 on 2026-02-11 10:14

from django.db import migrations, models
from ..migration_helpers import forward_refrain_pos, backward_refrain_pos


class Migration(migrations.Migration):

    dependencies = [
        ('chants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='chorus_after',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            forward_refrain_pos,
            backward_refrain_pos,
        ),
        migrations.RemoveField(
            model_name='song',
            name='refrain_pos',
        ),
    ]
