# Generated by Django 5.2.1 on 2025-05-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventoccurrence",
            name="event",
        ),
        migrations.DeleteModel(
            name="EventException",
        ),
        migrations.DeleteModel(
            name="EventOccurrence",
        ),
    ]
