# Generated by Django 5.2.1 on 2025-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0002_remove_eventoccurrence_event_delete_eventexception_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(),
        ),
    ]
