# Generated by Django 5.2.1 on 2025-09-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0004_remove_event_is_recurring_occurrence"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Occurrence",
            new_name="Date",
        ),
        migrations.RenameModel(
            old_name="Event",
            new_name="Recurrence",
        ),
    ]
