# Generated by Django 5.2.1 on 2025-10-02 16:48

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0005_rename_occurrence_date_rename_event_recurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="end_date",
            field=models.DateField(blank=True, db_column="end_date", null=True),
        ),
        migrations.RenameField(
            model_name="date",
            old_name="end_date",
            new_name="_end_date",
        ),
        migrations.AlterField(
            model_name="date",
            name="end_time",
            field=models.TimeField(blank=True, db_column="end_time", null=True),
        ),
        migrations.RenameField(
            model_name="date",
            old_name="end_time",
            new_name="_end_time",
        ),
        migrations.AlterField(
            model_name="date",
            name="start_time",
            field=models.TimeField(blank=True, db_column="start_time", null=True),
        ),
        migrations.RenameField(
            model_name="date",
            old_name="start_time",
            new_name="_start_time",
        ),
        migrations.RemoveField(
            model_name="recurrence",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="recurrence",
            name="start_date",
        ),
        migrations.AddField(
            model_name="date",
            name="_title",
            field=models.CharField(blank=True, db_column="title", max_length=200),
        ),
        migrations.AlterField(
            model_name="recurrence",
            name="recurrence",
            field=recurrence.fields.RecurrenceField(),
        ),
    ]
