# Generated by Django 5.2.1 on 2025-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0006_alter_date_end_date_rename_end_date_date__end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurrence",
            name="end_time",
            field=models.TimeField(blank=True, db_column="end_time", null=True),
        ),
        migrations.RenameField(
            model_name="recurrence",
            old_name="end_time",
            new_name="_end_time",
        ),
    ]
