# Generated by Django 5.2.1 on 2025-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0007_alter_recurrence_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("official_name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
