# Generated by Django 5.2.1 on 2025-10-14 08:12

import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0008_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedFeast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("recurrence", recurrence.fields.RecurrenceField()),
            ],
        ),
        migrations.CreateModel(
            name="MovableFeast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=200)),
            ],
        ),
    ]
