# Generated by Django 5.2.1 on 2025-10-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0009_alter_recurrence_end_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recurrence",
            old_name="_end_time",
            new_name="end_time",
        ),
        migrations.AlterField(
            model_name="recurrence",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
