# Generated by Django 5.2.1 on 2026-01-29 13:57

import dates.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0010_rename__end_time_recurrence_end_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENTS", "Announcements"),
                            ("MASSES", "Masses"),
                        ],
                        max_length=15,
                    ),
                ),
                ("days_before", models.IntegerField(default=0)),
                ("days_after", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="fixedfeast",
            name="recurrence",
            field=dates.fields.RecurrenceField(),
        ),
        migrations.AlterField(
            model_name="recurrence",
            name="recurrence",
            field=dates.fields.RecurrenceField(),
        ),
    ]
