# Generated by Django 5.2.1 on 2026-02-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0011_bulletin_alter_fixedfeast_recurrence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Celebrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        unique=True,
                        verbose_name="Abréviation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="date",
            name="ignored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="date",
            name="celebrant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dates.celebrant",
            ),
        ),
    ]
