# Generated by Django 5.2.1 on 2026-02-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dates", "0012_celebrant_date_ignored_date_celebrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="cancelled",
            field=models.BooleanField(default=False, verbose_name="Annulé"),
        ),
        migrations.AddField(
            model_name="date",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
    ]
